### PR TITLE
Detecting the available RAM in the system

### PR DESCRIPTION
**Pull request by brunohpaiva**
*Need to test in MacOS and Linux*

- Optimize imports
- Getting available RAM in the system

### CODE REVIEW

**Comment by ghost** [comment]
I'm going to test on macOS now

**Comment by ghost** [comment]
Just waiting for maven to download depends.

**Comment by ghost** [comment]
@brunohpaiva Works perfectly
image

**Comment by brunohpaiva** [comment]
Oh, thanks for the help
I'll try to test it on linux

**Comment by Cubxity** [comment]
Isn't OS management factory for oracle vms only?

**Comment by brunohpaiva** [comment]
So.. tomorrow I'll test it using other JVMs
nothing that a try catch does not solve :c

**Pull request closed without merging**
