### PR TITLE
Fix vulnerable dependencies 

### PR DESCRIPTION
**Pull request by RDIL**

### CODE REVIEW

**Comment by RDIL** [comment]
@Cubxity

**Comment by Cubxity** [comment]
iirc that http client will conflict with mc's http client

**Comment by RDIL** [comment]
So I should only update logback-classic @Cubxity?

**Comment by Cubxity** [comment]
[https://github.com/HyperiumClient/Installer/commit/c468852a3d1ef257c0bacd54a96a2aed0e2666bb](url)

**Pull request closed without merging**
